# Generated by Django 3.1.5 on 2021-02-18 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
